--  create table ============

-- DROP TABLE IF EXISTS `LD_ORDER`;

CREATE TABLE `LD_ORDER` (
  `ID` bigint(20) NOT NULL DEFAULT '0',
  `CREATED` bigint(20) DEFAULT NULL,
  `LAST_UPDATE` bigint(20) DEFAULT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `SHOP_ID` bigint(20) DEFAULT NULL,
  `CUSTOMER_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `LD_ORDER` ADD UNIQUE INDEX IDX_LD_ORDER_ID ( `id` );

-- DROP TABLE IF EXISTS `LD_ORDER_ITEM`;
CREATE TABLE `LD_ORDER_ITEM` (
  `ID` bigint(20) NOT NULL DEFAULT '0',
  `CREATED` bigint(20) DEFAULT NULL,
  `LAST_UPDATE` bigint(20) DEFAULT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `ORDER_ID` bigint(20) DEFAULT NULL,
  `PRODUCT_ID` bigint(20) DEFAULT NULL,
  `PRODUCT_NAME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

--SQL ALTER TABLE
ALTER TABLE usertb ADD status varchar(10);



